//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ct_dondat
    {
        public int ID { get; set; }
        public int MaDonDat { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual dondat dondat { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
