//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dondat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dondat()
        {
            this.ct_dondat = new HashSet<ct_dondat>();
        }
    
        public int MaDonDat { get; set; }
        public string TenDangNhap { get; set; }
        public string TrangThai { get; set; }
        public string NoiGiao { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_dondat> ct_dondat { get; set; }
        public virtual thanhvien thanhvien { get; set; }
    }
}
