//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart_shop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smart_shopEntities : DbContext
    {
        public smart_shopEntities()
            : base("name=smart_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<binhluan> binhluans { get; set; }
        public virtual DbSet<ct_dondat> ct_dondat { get; set; }
        public virtual DbSet<danhgia> danhgias { get; set; }
        public virtual DbSet<dondat> dondats { get; set; }
        public virtual DbSet<loaisp> loaisps { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thanhvien> thanhviens { get; set; }
        public virtual DbSet<nhanvien> nhanviens { get; set; }
    }
}
