//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smart_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.binhluans = new HashSet<binhluan>();
            this.ct_dondat = new HashSet<ct_dondat>();
            this.danhgias = new HashSet<danhgia>();
        }
    
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string TenSanPham_KhongDau { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<float>GiamGia { get; set; }
        public string HinhAnh1 { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string HinhAnh4 { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string ThongTin { get; set; }
        public Nullable<int> MaLoaiSP { get; set; }
        public Nullable<int> Man { get; set; }
        public Nullable<int> Woman { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<binhluan> binhluans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ct_dondat> ct_dondat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danhgia> danhgias { get; set; }
        public virtual loaisp loaisp { get; set; }
    }
}
